apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: metakube-all
  namespace: default
spec:
  commonName: '*.workshop.metakube.org'
  dnsNames:
    - '*.workshop.metakube.org'
  secretName: metakube-tls-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
